# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-04 02:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20190803_2101'),
        ('users', '0002_user_email_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20, verbose_name='地址名称')),
                ('receive', models.CharField(max_length=20, verbose_name='收件人')),
                ('place', models.CharField(max_length=50, verbose_name='地址')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机')),
                ('tel', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='固定电话')),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='邮箱')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_address', to='areas.Areas', verbose_name='市')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_address', to='areas.Areas', verbose_name='区')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province_address', to='areas.Areas', verbose_name='省')),
            ],
            options={
                'verbose_name': '地址',
                'db_table': 'tb_address',
                'verbose_name_plural': '地址',
                'ordering': ['-update_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用rel户', 'verbose_name_plural': '用rel户'},
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
